# Generated by Django 4.0.3 on 2022-04-09 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='padre',
            old_name='name',
            new_name='nombre',
        ),
    ]
