# Generated by Django 4.0.3 on 2022-04-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0002_rename_name_estudiante_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='genero',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='padre',
            name='genero',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Other')], max_length=1),
        ),
    ]
